"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, ClipboardList, HeartPulse, ShieldCheck } from "lucide-react";

const urgentSigns = ["Trouble breathing, severe chest pain, or blue/grey lips","Fainting, a new seizure, confusion, or sudden weakness on one side","Severe bleeding, a serious injury, or thoughts of harming yourself or someone else"];
type PractitionerCard = { name: string; role: string; phone: string; image?: string };
const defaultPractitioners: PractitionerCard[] = [
  {name:"Dr Emil Mgwami",role:"Medical Doctor (MD)",phone:"+255623555127"},
  {name:"Richard Kinyaha",role:"Dentist",phone:"+255620607399",image:"/practitioners/richard-kinyaha.jpg"},
  {name:"Moses Masika",role:"Medical Laboratory Professional",phone:"+255734717630",image:"/practitioners/moses-masika.jpg"},
  {name:"Mussa Kihayile",role:"Registered Nurse (RN)",phone:"+255778652916"},
  {name:"Sudi Zaidi",role:"Dentist (DDS)",phone:"+255679279037",image:"/practitioners/sudi-zaidi.png"},
  {name:"Rashid",role:"Medical Doctor (MD)",phone:"+255622269916",image:"/practitioners/rashid.jpg"},
];
const healthLibrary = [
  {title:"Tanzania Ministry of Health Guidelines",description:"Official Ministry publications, strategies, and health resources for Tanzania.",href:"https://moh.go.tz/strategies"},
  {title:"Patient Safety",description:"Learn why clear information, questions, and qualified care matter for safer health decisions.",href:"https://www.who.int/news-room/fact-sheets/detail/patient-safety"},
  {title:"Emergency Warning Signs",description:"Trouble breathing, severe chest pain, fainting, major bleeding, confusion, or sudden weakness need urgent care.",href:"https://www.who.int/news-room/questions-and-answers/item/coronavirus-disease-covid-19-home-care-for-families-and-caregivers"},
];
const practitionerLanguages = "Kiswahili and English";
const practitionerHours = "Monday–Saturday, 08:00–17:00";

export default function ClinicalAssistantPage() {
  const [practitioners,setPractitioners]=useState<PractitionerCard[]>(defaultPractitioners);
  const [language,setLanguage]=useState<"en"|"sw">("en"); const [name,setName]=useState(""); const [age,setAge]=useState(""); const [location,setLocation]=useState("");
  const [symptoms,setSymptoms]=useState(""); const [duration,setDuration]=useState(""); const [concerns,setConcerns]=useState("");
  const [showSummary,setShowSummary]=useState(false); const [guidance,setGuidance]=useState(""); const [followUp,setFollowUp]=useState(""); const [conversation,setConversation]=useState<string[]>([]); const [error,setError]=useState(""); const [isLoading,setIsLoading]=useState(false);
  useEffect(()=>{fetch("/api/practitioners").then(response=>response.json()).then(data=>{if(Array.isArray(data.practitioners)&&data.practitioners.length){setPractitioners(data.practitioners.map((item:{name:string;role:string;phone:string;image_url?:string|null})=>({name:item.name,role:item.role,phone:item.phone,image:item.image_url||undefined})));}}).catch(()=>{});},[]);
  function createSummary(event: FormEvent<HTMLFormElement>){event.preventDefault();setShowSummary(true);setGuidance("");setError("");}
  function summaryText(){return ["JUSTCOSTA VISIT SUMMARY",name ? "PATIENT NAME: "+name : "", "AGE: "+age,location ? "LOCATION: "+location : "","SYMPTOMS: "+symptoms,"WHEN IT BEGAN OR CHANGED: "+duration,concerns ? "QUESTIONS OR WORRIES: "+concerns : ""].filter(Boolean).join("\n\n");}
  function downloadSummary(){const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([summaryText()],{type:"text/plain"}));link.download="justcosta-visit-summary.txt";link.click();URL.revokeObjectURL(link.href);}
  function printSummary(){const printWindow=window.open("","_blank","width=760,height=900");if(!printWindow)return;printWindow.document.write("<!doctype html><html><head><title>JustCosta Visit Summary</title><style>body{font-family:Arial,sans-serif;line-height:1.6;padding:32px;color:#0f172a}h1{color:#0e7490;white-space:pre-line}pre{font:inherit;white-space:pre-wrap}</style></head><body><h1>JUSTCOSTA VISIT SUMMARY</h1><pre>"+summaryText().replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")+"</pre></body></html>");printWindow.document.close();printWindow.focus();printWindow.print();}
  async function getGuidance(message = ""){
    setIsLoading(true);setError("");
    try{
      const conversationContext=[guidance ? "AI initial guidance: "+guidance : "",...conversation.slice(-6)].filter(Boolean).join("\n");
      const response=await fetch("/api/clinical-assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({language,age,location,symptoms,duration,concerns:message ? concerns+"\n\nConversation so far:\n"+conversationContext+"\n\nPatient follow-up question: "+message : concerns})});
      const data=await response.json();
      if(!response.ok) throw new Error(data.error||"THE AI SERVICE COULD NOT RESPOND RIGHT NOW.");
      const answer=data.guidance||"NO GUIDANCE WAS RETURNED. PLEASE SPEAK WITH A QUALIFIED CLINICIAN.";
      if(message){setConversation(items=>[...items,"You: "+message,"AI: "+answer]);setFollowUp("");}else{setGuidance(answer);setConversation([]);}
    }catch(e){setError(e instanceof Error?e.message:"SOMETHING WENT WRONG. PLEASE TRY AGAIN LATER.");}finally{setIsLoading(false);}
  }
  const input="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-950 outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100";
  function formatGuidance(text:string){return text.replace(/\*/g,"").split("\n").filter(Boolean).map((line,index)=>{const important=/^(IMPORTANT|NEXT STEP|URGENT HELP|MUHIMU|HATUA INAYOFUATA|HUDUMA YA HARAKA):/i.test(line.trim());return <p key={index} className={important?"font-extrabold text-cyan-900":"font-medium"}>{line}</p>;});}
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6"><div className="mx-auto max-w-4xl">
    <Link href="/" className="inline-flex items-center gap-2 font-semibold text-slate-700 hover:text-cyan-700"><ArrowLeft className="h-4 w-4"/>BACK TO JUSTCOSTA</Link>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/60 sm:p-10">
      <div className="flex gap-5"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-700"><HeartPulse className="h-7 w-7"/></div><div><p className="font-bold uppercase tracking-[.18em] text-cyan-700">PATIENT HEALTH VISIT HELPER</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">Prepare for your healthcare visit.</h1><p className="mt-3 text-slate-600">Organise your particulars, symptoms and questions before speaking with a qualified healthcare professional.</p></div></div>
      <div className="mt-6 flex flex-wrap items-center gap-3 rounded-xl border border-cyan-200 bg-cyan-50 p-4"><p className="font-bold text-cyan-950">AI RESPONSE LANGUAGE / LUGHA YA MAJIBU YA AI:</p><button type="button" onClick={()=>setLanguage("en")} className={language==="en"?"rounded-lg bg-cyan-700 px-4 py-2 font-bold text-white":"rounded-lg border border-cyan-300 bg-white px-4 py-2 font-bold text-cyan-900"}>English</button><button type="button" onClick={()=>setLanguage("sw")} className={language==="sw"?"rounded-lg bg-cyan-700 px-4 py-2 font-bold text-white":"rounded-lg border border-cyan-300 bg-white px-4 py-2 font-bold text-cyan-900"}>Kiswahili</button><p className="text-sm font-medium text-slate-700">{language==="sw"?"AI itajibu kwa Kiswahili rahisi.":"AI will reply in simple English."}</p></div>
      <div className="mt-8 rounded-2xl border-2 border-red-300 bg-red-50 p-5"><div className="flex gap-3"><AlertTriangle className="mt-1 h-6 w-6 shrink-0 text-red-700"/><div><h2 className="font-extrabold uppercase text-red-900">GET URGENT HELP NOW IF YOU HAVE:</h2><ul className="mt-3 space-y-2 font-semibold text-red-900">{urgentSigns.map(x=><li key={x}>• {x}</li>)}</ul><p className="mt-3 font-extrabold text-red-900">GO TO THE NEAREST EMERGENCY DEPARTMENT OR CONTACT YOUR LOCAL EMERGENCY SERVICE.</p></div></div></div>
      <form onSubmit={createSummary} className="mt-8 space-y-5"><div><h2 className="text-xl font-extrabold uppercase">Patient particulars</h2><p className="mt-1 font-semibold text-slate-600">YOUR NAME STAYS ON THIS PAGE AND IS NOT SENT TO THE AI.</p></div>
        <div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">PATIENT NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="Optional" className={input}/></label><label className="font-bold">AGE<input value={age} onChange={e=>setAge(e.target.value)} type="number" min="0" max="130" required className={input}/></label></div>
        <label className="font-bold">LOCATION<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Region, district, or ward (optional)" className={input}/></label>
        <div className="border-t border-slate-200 pt-5"><h2 className="text-xl font-extrabold uppercase">Your visit notes</h2><p className="font-semibold text-slate-600">YOUR NOTES ARE NOT STORED BY THIS WEBSITE.</p></div>
        <label className="font-bold">WHAT SYMPTOMS OR CONCERNS WOULD YOU LIKE TO DISCUSS?<textarea value={symptoms} onChange={e=>setSymptoms(e.target.value)} required rows={4} className={input}/></label>
        <label className="font-bold">WHEN DID THIS BEGIN, AND HAS IT CHANGED?<textarea value={duration} onChange={e=>setDuration(e.target.value)} required rows={3} className={input}/></label>
        <label className="font-bold">WHAT QUESTIONS OR WORRIES DO YOU HAVE?<textarea value={concerns} onChange={e=>setConcerns(e.target.value)} rows={3} className={input}/></label>
        <button className="inline-flex items-center gap-2 rounded-xl bg-cyan-700 px-5 py-3 font-extrabold text-white hover:bg-cyan-800"><ClipboardList className="h-5 w-5"/>CREATE MY VISIT SUMMARY</button>
      </form>
      {showSummary&&<section className="mt-8 rounded-2xl border-2 border-cyan-200 bg-cyan-50 p-6"><h2 className="text-xl font-extrabold uppercase text-cyan-950">Your visit summary</h2><div className="mt-4 space-y-3">{name&&<p><b>PATIENT NAME:</b> {name}</p>}<p><b>AGE:</b> {age}</p>{location&&<p><b>LOCATION:</b> {location}</p>}<p><b>SYMPTOMS:</b> {symptoms}</p><p><b>WHEN IT BEGAN OR CHANGED:</b> {duration}</p>{concerns&&<p><b>QUESTIONS OR WORRIES:</b> {concerns}</p>}</div><div className="mt-5 flex gap-3 rounded-xl bg-white p-4 font-semibold text-slate-700"><ShieldCheck className="h-5 w-5 shrink-0 text-cyan-700"/><p>IMPORTANT: IF YOU CHOOSE AI GUIDANCE, ONLY YOUR AGE, BROAD LOCATION, SYMPTOMS, TIMING AND CONCERNS ARE SENT TO THE AI SERVICE. YOUR NAME IS NOT SENT.</p></div><button type="button" onClick={()=>getGuidance()} disabled={isLoading} className="mt-5 rounded-xl bg-cyan-700 px-5 py-3 font-extrabold text-white disabled:opacity-60">{isLoading?"GETTING AI GUIDANCE...":"GET AI GUIDANCE"}</button>{error&&<p className="mt-4 font-extrabold text-red-700">{error}</p>}{guidance&&<div className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-5 leading-7">{formatGuidance(guidance)}</div>}</section>}
      {showSummary&&<div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={downloadSummary} className="rounded-xl border border-cyan-700 bg-white px-4 py-2 font-bold text-cyan-800">DOWNLOAD SUMMARY</button><button type="button" onClick={printSummary} className="rounded-xl border border-cyan-700 bg-white px-4 py-2 font-bold text-cyan-800">PRINT SUMMARY</button></div>}
      {showSummary && <section className="mt-6 rounded-2xl border border-cyan-200 bg-white p-5"><h2 className="font-bold text-cyan-900">CONTINUE THE CONVERSATION</h2><p className="mt-1 text-sm text-slate-600">{guidance ? "Ask a follow-up question. Your name is not sent to the AI." : "FIRST, SELECT GET AI GUIDANCE ABOVE. THEN YOU CAN ASK FOLLOW-UP QUESTIONS HERE."}</p>{guidance && <div className="mt-4 space-y-3">{conversation.map((message,index)=><p key={index} className={message.startsWith("AI:") ? "rounded-lg bg-cyan-50 p-3" : "rounded-lg bg-slate-100 p-3 font-medium"}>{message}</p>)}</div>}<textarea value={followUp} onChange={e=>setFollowUp(e.target.value)} placeholder={guidance ? "Ask another question or add more information" : "Get AI guidance first"} disabled={!guidance} rows={3} className={input}/><div className="mt-3 flex gap-3"><button type="button" disabled={!guidance||!followUp.trim()||isLoading} onClick={()=>getGuidance(followUp.trim())} className="rounded-xl bg-cyan-700 px-4 py-2 font-bold text-white disabled:opacity-50">{isLoading?"SENDING...":"SEND"}</button><button type="button" onClick={()=>{setConversation([]);setFollowUp("");setGuidance("");setShowSummary(false);}} className="rounded-xl border border-slate-300 px-4 py-2 font-bold text-slate-700">START NEW CONVERSATION</button></div></section>}
      <section className="mt-8 rounded-2xl border-2 border-cyan-200 bg-cyan-50 p-6"><h2 className="text-xl font-extrabold uppercase text-cyan-950">Speak to a medical practitioner</h2><p className="mt-2 text-slate-700">You may choose a practitioner below and call directly if they are available.</p><p className="mt-2 font-bold text-red-800">FOR URGENT OR LIFE-THREATENING SYMPTOMS, GO TO THE NEAREST EMERGENCY DEPARTMENT OR CONTACT LOCAL EMERGENCY SERVICES. THIS IS NOT AN EMERGENCY CALL SERVICE.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{practitioners.map(practitioner=><article key={practitioner.phone} className="rounded-xl border border-cyan-200 bg-white p-4"><div className="flex items-center gap-3">{practitioner.image&&<img src={practitioner.image} alt={practitioner.name} className="h-16 w-16 rounded-full object-cover ring-2 ring-cyan-200"/>}<div><h3 className="font-extrabold text-slate-950">{practitioner.name}</h3><p className="mt-1 font-semibold text-cyan-800">{practitioner.role}</p></div></div><dl className="mt-4 space-y-2 text-sm text-slate-700"><div><dt className="font-bold text-slate-950">PROFESSIONAL CATEGORY</dt><dd>{practitioner.role}</dd></div><div><dt className="font-bold text-slate-950">LANGUAGES</dt><dd>{practitionerLanguages}</dd></div><div><dt className="font-bold text-slate-950">CONSULTATION HOURS</dt><dd>{practitionerHours}</dd></div><div><dt className="font-bold text-emerald-800">AVAILABILITY</dt><dd className="font-semibold text-emerald-800">AVAILABLE DURING WORKING HOURS</dd></div></dl><p className="mt-3 text-slate-700">{practitioner.phone}</p><a href={"tel:"+practitioner.phone} className="mt-3 inline-flex rounded-lg bg-cyan-700 px-4 py-2 font-extrabold text-white hover:bg-cyan-800">CALL PRACTITIONER</a></article>)}</div></section>
      <section className="mt-8 rounded-2xl border-2 border-slate-200 bg-white p-6"><h2 className="text-xl font-extrabold uppercase text-slate-950">Trusted Health Library / Maktaba ya Afya</h2><p className="mt-2 text-slate-700">Reliable information to help you prepare for care. These resources do not replace an assessment by a qualified practitioner.</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{healthLibrary.map(resource=><a key={resource.href} href={resource.href} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 p-4 transition hover:border-cyan-500 hover:bg-cyan-50"><h3 className="font-extrabold text-cyan-900">{resource.title}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{resource.description}</p><p className="mt-3 font-bold text-cyan-700">OPEN RESOURCE →</p></a>)}</div></section>
      <div className="mt-8 flex gap-3 rounded-2xl border-2 border-slate-300 bg-slate-100 p-5 font-semibold text-slate-800"><ShieldCheck className="h-5 w-5 shrink-0 text-cyan-700"/><p><b>IMPORTANT:</b> THIS TOOL SUPPORTS PREPARATION FOR A HEALTHCARE VISIT. IT IS <b>NOT</b> A DIAGNOSIS, TREATMENT PLAN, PRESCRIPTION OR EMERGENCY SERVICE.</p></div>
    </section></div></main>;
}
